// Mocks generated by Mockito 5.4.5 from annotations
// in weather_app/test/repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/dataLayer/networks/remote/dio_helper.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DioHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioHelper extends _i1.Mock implements _i2.DioHelper {
  MockDioHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get({
    String? base,
    required String? url,
    dynamic data,
    dynamic query,
    dynamic headers,
    String? token,
    _i4.CancelToken? cancelToken,
    Duration? timeOut,
    bool? isMultipart = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {
              #base: base,
              #url: url,
              #data: data,
              #query: query,
              #headers: headers,
              #token: token,
              #cancelToken: cancelToken,
              #timeOut: timeOut,
              #isMultipart: isMultipart,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);
}
